---
# Configuration: https://dependabot.com/docs/config-file/
# Docs: https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2

updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
  cooldown-days: 7
  allow:
  - dependency-type: all
  commit-message:
    prefix: ':arrow_up:'
  open-pull-requests-limit: 50
  groups:
    pip-dependencies:
      patterns:
      - "*"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  cooldown-days: 7
  allow:
  - dependency-type: all
  commit-message:
    prefix: ':arrow_up:'
  open-pull-requests-limit: 50
  groups:
    github-actions-dependencies:
      patterns:
      - "*"

- package-ecosystem: docker
  directory: ./
  schedule:
    interval: weekly
  cooldown-days: 7
  allow:
  - dependency-type: all
  commit-message:
    prefix: ':arrow_up:'
  open-pull-requests-limit: 50
  groups:
    docker-dependencies:
      patterns:
      - "*"
