---
# Docs: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2

updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  allow:
  - dependency-type: all
  commit-message:
    prefix: ':arrow_up:'
  open-pull-requests-limit: 50
  groups:
    pip-dependencies:
      patterns:
      - "*"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  allow:
  - dependency-type: all
  commit-message:
    prefix: ':arrow_up:'
  open-pull-requests-limit: 50
  groups:
    github-actions-dependencies:
      patterns:
      - "*"

- package-ecosystem: docker
  directory: ./
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  allow:
  - dependency-type: all
  commit-message:
    prefix: ':arrow_up:'
  open-pull-requests-limit: 50
  groups:
    docker-dependencies:
      patterns:
      - "*"
