---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-added-large-files
  - id: debug-statements
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'dd18dad857d6133e90bbe478f4f2f22ec0030269'  # frozen: v22.1.5
  hooks:
  - id: clang-format
    exclude: "^(dune/xt/test/gtest/|pybind11)"
- repo: https://github.com/google/yamlfmt
  rev: b5ca1890231d5e1e5181fef75a1be609d1e25029  # frozen: v0.21.0
  hooks:
  - id: yamlfmt
    exclude: ".clang-format|.clang-tidy"
- repo: https://github.com/rhysd/actionlint
  rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # frozen: v1.7.12
  hooks:
  - id: actionlint
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 22f0422809455ec89ffdcf5a00170ba816e42ddb  # frozen: v0.15.16
  hooks:
  - id: ruff
  - id: ruff-format
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: 'e2c2116d86a80e72e7146a06e68b7c228afc6319'  # frozen: v0.6.13
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml>=5.1] # see https://github.com/cheshirekow/cmake-format-precommit/pull/4#issuecomment-943444582
    exclude: "config.h.cmake|pybind11"
    args: ["-i", "--config-files=.cmake_format.py"]
  - id: cmake-lint
    additional_dependencies: [pyyaml>=5.1] # see https://github.com/cheshirekow/cmake-format-precommit/pull/4#issuecomment-943444582
    exclude: "config.h.cmake|pybind11"
    args: ["--config-files=.cmake_format.py"]
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 943377262562a12b57292fc98fabd7dbf81451fe  # frozen: 0.37.2
  hooks:
  - id: check-github-actions
    additional_dependencies:
    - pip_system_certs==4.0
  - id: check-dependabot
    additional_dependencies:
    - pip_system_certs==4.0
- repo: https://github.com/Mateusz-Grzelinski/actionlint-py
  rev: c04ed26e40637cab1aa9879c693832a9c120fb20  # frozen: v1.7.12.24
  hooks:
  - id: actionlint
    additional_dependencies: [pyflakes>=3.0.1, shellcheck-py>=0.9.0.5]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
