# ~~~
# This file is part of the dune-gdt project:
#   https://zivgitlab.uni-muenster.de/ag-ohlberger/dune-community/dune-gdt
# Copyright 2010-2021 dune-gdt developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
#          with "runtime exception" (http://www.dune-project.org/license.html)
# Authors:
#   Felix Schindler (2011 - 2014, 2016 - 2021)
#   René Fritze     (2009, 2011 - 2022)
#   Tobias Leibner  (2015, 2018 - 2022)
#   f_albr01        (2010)
#   felix.albrecht  (2011)
#   m_droh01        (2011)
#   nolte           (2011)
# ~~~

Module: dune-gdt
# USE DUNE_GDT_GIT_VERSION in cmake scripts instead
Version: SET.BY.CMAKE
Maintainer: dune-gdt@dune-community.ovh
Depends: dune-common (>= 2.8) dune-geometry (>= 2.8) dune-grid (>= 2.8) dune-istl (>= 2.8) dune-localfunctions (>= 2.8)
Suggests: dune-testtools (>= 2.8) dune-alugrid (>= 2.8) dune-grid-glue (>= 2.8) dune-uggrid (>= 2.8)
