# This file is part of the dune-gdt project:
#   https://github.com/dune-community/dune-gdt-super
# The copyright lies with the authors of this file (see below).
# License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
# Authors:
#   Rene Milk       (2016)

sudo: required
dist: xenial
language: generic

install:
  - sudo -E aptitude install -y python3-six python3-pip

script:
  - cd ${TRAVIS_BUILD_DIR}
  - git submodule update --init --recursive
  - git submodule status
  - ./bin/check_environments.py

git:
  # we do that manually in script section to be able to use our own git binary
  submodules: false

notifications:
  email:
    on_success: change
    on_failure: change
