language: generic
sudo: required
dist: xenial

addons:
  apt:
    sources: &commonsources
    packages: &commonpackages
    - cmake
    - cmake-data

before_script:
    - git clone --branch ${DUNE_BRANCH} https://github.com/dune-mirrors/dune-common.git
    - sudo -E apt-get build-dep libdune-common-2.2.1 -y
script:
    - set -e
    - |
        for i in $(git ls-files | \grep -Ev "README|.travis.yml") ; do
            echo "checking ${i}"
            bash ${i}
            ./dune-common/bin/dunecontrol --opts=${i} info 1> /dev/null
            pushd dune-common
            git clean -xdf
            popd
        done

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  except:
    - gh-pages

matrix:
    include:
    - env: DUNE_BRANCH=master
    - env: DUNE_BRANCH=releases/2.3
    - env: DUNE_BRANCH=releases/2.4
    - env: DUNE_BRANCH=releases/2.5
    - env: DUNE_BRANCH=releases/2.6
