# This file is generated by .CMakePresets.json.in

set(CMAKE_CXX_STANDARD 20)
string(APPEND CMAKE_CXX_FLAGS_INIT " ")
set(VCPKG_CXX_FLAGS " ")
string(APPEND CMAKE_CXX_FLAGS_DEBUG_INIT " -Og -g")
set(VCPKG_CXX_FLAGS_DEBUG " -Og -g")
string(APPEND CMAKE_CXX_FLAGS_RELEASE_INIT " -O3")
set(VCPKG_CXX_FLAGS_RELEASE " -O3")
string(APPEND CMAKE_CXX_FLAGS_RELWITHCHECKS_INIT " -O3 -g")
set(VCPKG_CXX_FLAGS_RELWITHCHECKS " -O3 -g")
string(APPEND CMAKE_CXX_FLAGS_COVERAGE_INIT " -Og -g -fprofile-arcs -ftest-coverage")
set(VCPKG_CXX_FLAGS_COVERAGE " -Og -g -fprofile-arcs -ftest-coverage")
