# this gets our custom flags get passed to all `try_compile` calls ensuring any incompat/error is caught early
list(
  APPEND
  CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
  VCPKG_CRT_LINKAGE
  VCPKG_TARGET_ARCHITECTURE
  VCPKG_SET_CHARSET_FLAG
  VCPKG_C_FLAGS
  VCPKG_CXX_FLAGS
  VCPKG_C_FLAGS_DEBUG
  VCPKG_CXX_FLAGS_DEBUG
  VCPKG_C_FLAGS_RELEASE
  VCPKG_CXX_FLAGS_RELEASE
  VCPKG_LINKER_FLAGS
  VCPKG_LINKER_FLAGS_RELEASE
  VCPKG_LINKER_FLAGS_DEBUG
  VCPKG_PLATFORM_TOOLSET)
