# ~~~
# This file is part of the dune-gdt project:
#   https://github.com/dune-gdt/dune-gdt
# Copyright 2010-2026 dune-gdt developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
#          with "runtime exception" (http://www.dune-project.org/license.html)
# Authors:
#   René Fritze (2026)
# ~~~
"""Scenario 3: DoF-count and interpolation-point properties of the discrete function spaces.

The C++ counterparts (dune/gdt/test/spaces/spaces_*.cc) instantiate one typed test suite per
(grid list x polynomial order); adding an order means another block of TYPED_TESTs compiled in
every grid variant. The bindings expose the same space factories with the order as a *runtime*
argument, so the (grid x order) product below is generated by hypothesis and costs no compile
time at all. The expectations are closed-form DoF counts on structured grids, which pin the
C++ mapper logic (dune/gdt/spaces/mapper/) far harder than the smoke assertions they replace.
"""

import math
import subprocess
import sys
import textwrap

import numpy as np
import pytest
from hypothesis import given
from hypothesis import strategies as st

from dune.xt.test.hypothesis_strategies import GRID_COMBINATIONS, grid_specs, has_grid

# Skip cleanly on builds that bind no grids at all; element-specific tests below add their own
# guard so a build without, e.g., ALUGrid (no simplex grids) skips just those.
pytestmark = pytest.mark.skipif(
    not GRID_COMBINATIONS, reason="no grid bindings available in this build"
)

_needs_cube = pytest.mark.skipif(
    not has_grid(element="cube"), reason="no cube grid bindings available in this build"
)
_needs_simplex = pytest.mark.skipif(
    not has_grid(element="simplex"),
    reason="no simplex grid bindings available in this build",
)


# binomial(order + dim, dim): dimension of P_k on a d-simplex
def _p_k_dim(order, dim):
    return math.comb(order + dim, dim)


# The ContinuousMapper throws Dune::NotImplemented for order > 2 on (at least) the simplicial
# ALU grids (dune/gdt/spaces/mapper/continuous.hh, see the comment in global_index); the cube
# grids support order 3. Encoding the boundary here makes it part of the tested contract: if
# the mapper ever learns order > 2, the strategy below is the only place to widen.
def _cg_orders(spec, top=3):
    return st.integers(1, min(top, 2) if spec.element == "simplex" else top)


@_needs_cube
@given(spec=grid_specs(elements=("cube",)), order=st.integers(1, 3))
def test_cg_dof_count_on_cube_grids(spec, order):
    from dune.gdt import ContinuousLagrangeSpace

    space = ContinuousLagrangeSpace(spec.make_grid(), order=order)
    # tensor-product Lagrange nodes: order*n + 1 per axis
    assert space.num_DoFs == int(np.prod([order * n + 1 for n in spec.num_elements]))
    assert space.min_polorder == space.max_polorder == order


@_needs_simplex
@given(spec=grid_specs(elements=("simplex",)))
def test_p1_cg_dofs_are_the_vertices_on_simplicial_grids(spec):
    from dune.gdt import ContinuousLagrangeSpace

    grid = spec.make_grid()
    space = ContinuousLagrangeSpace(grid, order=1)
    assert space.num_DoFs == grid.size(spec.dim)


@given(spec=grid_specs(), order=st.integers(0, 3))
def test_dg_dof_count_is_per_element(spec, order):
    from dune.gdt import DiscontinuousLagrangeSpace

    grid = spec.make_grid()
    space = DiscontinuousLagrangeSpace(grid, order=order)
    if spec.element == "cube":
        dofs_per_element = (order + 1) ** spec.dim  # Q_k
    else:
        dofs_per_element = _p_k_dim(order, spec.dim)  # P_k
    assert space.num_DoFs == grid.size(0) * dofs_per_element


@given(spec=grid_specs())
def test_fv_space_has_one_dof_per_element(spec):
    from dune.gdt import FiniteVolumeSpace

    grid = spec.make_grid()
    space = FiniteVolumeSpace(grid)
    assert space.num_DoFs == grid.size(0)
    assert space.min_polorder == space.max_polorder == 0


# This property crashes the interpreter with the current bindings: destroying the
# CommonDenseMatrix returned by SpaceInterface.interpolation_points segfaults (a plain
#   s = ContinuousLagrangeSpace(make_cube_grid(...), order=1); s.interpolation_points()
# followed by the object going out of scope is enough; found by the hypothesis run of this
# very test). The property is therefore exercised in a subprocess: a segfault fails *this
# test* instead of killing the whole pytest process, and the in-subprocess assertions still
# verify the property once the binding is fixed.
_INTERPOLATION_POINTS_PROPERTY = textwrap.dedent(
    """
    import numpy as np
    from dune.xt.test.hypothesis_strategies import GridSpec
    from dune.gdt import ContinuousLagrangeSpace

    spec = GridSpec(dim={dim}, element={element!r}, lower_left={lower!r}, upper_right={upper!r},
                    num_elements={num_elements!r})
    space = ContinuousLagrangeSpace(spec.make_grid(), order={order})
    points = np.array(space.interpolation_points(), copy=True)
    assert points.shape == (space.num_DoFs, {dim}), points.shape
    lower, upper = np.asarray(spec.lower_left), np.asarray(spec.upper_right)
    slack = 1e-12 * np.maximum(1.0, np.abs(upper - lower) + np.abs(lower))
    assert (points >= lower - slack).all()
    assert (points <= upper + slack).all()
    """
)


@pytest.mark.parametrize(
    "dim, element, order",
    [
        (1, "simplex", 1),
        (2, "cube", 2),
        (2, "simplex", 1),
        (3, "cube", 1),
        (3, "simplex", 2),
    ],
)
def test_cg_interpolation_points_match_dofs_and_lie_in_domain(dim, element, order):
    code = _INTERPOLATION_POINTS_PROPERTY.format(
        dim=dim,
        element=element,
        lower=(0.0,) * dim,
        upper=(1.0,) * dim,
        num_elements=(2,) * dim,
        order=order,
    )
    result = subprocess.run(
        [sys.executable, "-c", code], capture_output=True, text=True
    )
    if result.returncode < 0:
        pytest.xfail(
            "SpaceInterface.interpolation_points crashes on destruction of the returned "
            f"matrix (signal {-result.returncode}); known upstream binding bug found by this test"
        )
    assert result.returncode == 0, result.stderr


@given(data=st.data(), spec=grid_specs(max_elements_per_dim=3))
def test_num_dofs_grows_with_order_and_refinement(data, spec):
    from dune.gdt import ContinuousLagrangeSpace

    # order + 1 must stay within the mapper's limits (2 on simplicial grids, see _cg_orders)
    order = data.draw(
        _cg_orders(spec, top=3).map(lambda o: max(o - 1, 1)), label="order"
    )
    grid = spec.make_grid()
    coarse = ContinuousLagrangeSpace(grid, order=order)
    higher = ContinuousLagrangeSpace(grid, order=order + 1)
    assert higher.num_DoFs > coarse.num_DoFs
    grid.global_refine(1)
    refined = ContinuousLagrangeSpace(grid, order=order)
    assert refined.num_DoFs > coarse.num_DoFs


if __name__ == "__main__":
    from dune.xt.test.base import runmodule

    runmodule(__file__)
