# ~~~
# This file is part of the dune-gdt project:
#   https://github.com/dune-gdt/dune-gdt
# Copyright 2010-2026 dune-gdt developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#      or  GPL-2.0+ (http://opensource.org/licenses/gpl-license)
#          with "runtime exception" (http://www.dune-project.org/license.html)
# Authors:
#   René Fritze (2026)
# ~~~
"""Scenario 3: DoF-count and interpolation-point properties of the discrete function spaces.

The C++ counterparts (dune/gdt/test/spaces/spaces_*.cc) instantiate one typed test suite per
(grid list x polynomial order); adding an order means another block of TYPED_TESTs compiled in
every grid variant. The bindings expose the same space factories with the order as a *runtime*
argument, so the (grid x order) product below is generated by hypothesis and costs no compile
time at all. The expectations are closed-form DoF counts on structured grids, which pin the
C++ mapper logic (dune/gdt/spaces/mapper/) far harder than the smoke assertions they replace.
"""

import math
import subprocess
import sys
import textwrap

import numpy as np
import pytest
from hypothesis import given
from hypothesis import strategies as st

from dune.xt.test.hypothesis_strategies import (
    GRID_BINDINGS,
    GRID_COMBINATIONS,
    cg_scalar_dof_count,
    cg_vector_dof_count,
    dg_dof_count_on_mixed_grid,
    grid_specs,
    has_grid,
)

# Skip cleanly on builds that bind no grids at all; element-specific tests below add their own
# guard so a build without, e.g., ALUGrid (no simplex grids) skips just those.
pytestmark = pytest.mark.skipif(
    not GRID_COMBINATIONS, reason="no grid bindings available in this build"
)

_needs_cube = pytest.mark.skipif(
    not has_grid(element="cube"), reason="no cube grid bindings available in this build"
)
_needs_simplex = pytest.mark.skipif(
    not has_grid(element="simplex"),
    reason="no simplex grid bindings available in this build",
)
_needs_vector_grid = pytest.mark.skipif(
    not (has_grid(dim=2) or has_grid(dim=3)),
    reason="dim_range > 1 requires a 2d or 3d grid binding",
)


# binomial(order + dim, dim): dimension of P_k on a d-simplex
def _p_k_dim(order, dim):
    return math.comb(order + dim, dim)


# The ContinuousMapper throws Dune::NotImplemented for order > 2 on (at least) the simplicial
# ALU grids (dune/gdt/spaces/mapper/continuous.hh, see the comment in global_index); the cube
# grids support order 3. Encoding the boundary here makes it part of the tested contract: if
# the mapper ever learns order > 2, the strategy below is the only place to widen.
def _cg_orders(spec, top=3):
    return st.integers(1, min(top, 2) if spec.element == "simplex" else top)


@_needs_cube
@given(spec=grid_specs(elements=("cube",)), order=st.integers(1, 3))
def test_cg_dof_count_on_cube_grids(spec, order):
    from dune.gdt import ContinuousLagrangeSpace

    space = ContinuousLagrangeSpace(spec.make_grid(), order=order)
    # tensor-product Lagrange nodes: order*n + 1 per axis
    assert space.num_DoFs == cg_scalar_dof_count(order, spec.num_elements)
    assert space.min_polorder == space.max_polorder == order


@_needs_cube
@given(spec=grid_specs(elements=("cube",), dims=(2, 3)), order=st.integers(1, 3))
def test_vector_cg_dof_count_on_cube_grids(spec, order):
    """WP4 (#320): ContinuousLagrangeSpace(..., dim_range=Dim(d)) gets the same factory overload
    DiscontinuousLagrangeSpace/FiniteVolumeSpace already had; its DoF count is exactly d times the
    scalar space's (see cg_vector_dof_count).
    """
    from dune.gdt import ContinuousLagrangeSpace
    from dune.xt.grid import Dim

    grid = spec.make_grid()
    scalar_space = ContinuousLagrangeSpace(grid, order=order)
    vector_space = ContinuousLagrangeSpace(grid, order=order, dim_range=Dim(spec.dim))
    assert vector_space.num_DoFs == cg_vector_dof_count(
        order, spec.num_elements, spec.dim
    )
    assert vector_space.num_DoFs == spec.dim * scalar_space.num_DoFs


@_needs_simplex
@given(spec=grid_specs(elements=("simplex",)))
def test_p1_cg_dofs_are_the_vertices_on_simplicial_grids(spec):
    from dune.gdt import ContinuousLagrangeSpace

    grid = spec.make_grid()
    space = ContinuousLagrangeSpace(grid, order=1)
    assert space.num_DoFs == grid.size(spec.dim)


@given(spec=grid_specs(), order=st.integers(0, 3))
def test_dg_dof_count_is_per_element(spec, order):
    from dune.gdt import DiscontinuousLagrangeSpace

    grid = spec.make_grid()
    space = DiscontinuousLagrangeSpace(grid, order=order)
    if spec.element == "cube":
        dofs_per_element = (order + 1) ** spec.dim  # Q_k
    else:
        dofs_per_element = _p_k_dim(order, spec.dim)  # P_k
    assert space.num_DoFs == grid.size(0) * dofs_per_element


@_needs_vector_grid
@given(spec=grid_specs(dims=(2, 3), max_elements_per_dim=2), order=st.integers(1, 2))
def test_vector_dg_space_uses_the_dimwise_mapper(spec, order):
    """A vector-valued DiscontinuousLagrangeSpace numbers its DoFs dimension-wise.

    With dim_range > 1 the factory defaults dimwise_global_mapping to True, which routes the
    DiscontinuousMapper (dune/gdt/spaces/mapper/discontinuous.hh) through its per-range-dimension
    (else) branches -- construction/update_after_adapt and the global_indices used when a sparsity
    pattern is built. The scalar space exercises only the other side of those branches. The global
    DoF count is the scalar DG count replicated across the r = dim range components.
    """
    from dune.gdt import DiscontinuousLagrangeSpace, make_element_sparsity_pattern
    from dune.xt.grid import Dim

    r = spec.dim
    grid = spec.make_grid()
    space = DiscontinuousLagrangeSpace(grid, order=order, dim_range=Dim(r))
    assert space.dimwise_global_mapping is True
    assert space.num_DoFs == r * dg_dof_count_on_mixed_grid(grid, order)

    # building the element sparsity pattern walks the grid and asks the mapper for the global
    # indices of every element -- the dimwise (else) path of DiscontinuousMapper::global_indices.
    pattern = make_element_sparsity_pattern(space)
    assert pattern is not None


@given(spec=grid_specs())
def test_fv_space_has_one_dof_per_element(spec):
    from dune.gdt import FiniteVolumeSpace

    grid = spec.make_grid()
    space = FiniteVolumeSpace(grid)
    assert space.num_DoFs == grid.size(0)
    assert space.min_polorder == space.max_polorder == 0


@given(spec=grid_specs(conforming_only=True))
def test_rt_space_order_zero_works_higher_orders_are_a_documented_contract_limit(spec):
    """WP4 (#320): unlike the CG order boundary above (a subtle, grid-dependent mapper edge case),
    RaviartThomasSpace order > 0 is unconditionally rejected (dune/gdt/spaces/hdiv/raviart-thomas.hh):
    the higher-order local RT finite elements simply do not exist in this codebase yet. Encoding order=0
    as the only value exercised here keeps that contract visible to the property suite.

    conforming_only=True: the class doc comment (raviart-thomas.hh) only claims order 0 works "on
    simplices, cubes" without distinguishing conforming/nonconforming grids, so nonconforming ALU
    draws are excluded here rather than assumed to work; all three dims are otherwise exercised
    (1d is explicitly documented as working, unlike the CG vector test above which needs d > 1).
    """
    from dune.gdt import RaviartThomasSpace
    from dune.xt.common import DuneError

    grid = spec.make_grid()
    space = RaviartThomasSpace(grid, order=0)
    assert space.min_polorder == space.max_polorder == 0

    with pytest.raises(DuneError):
        RaviartThomasSpace(grid, order=1)


# This property crashes the interpreter with the current bindings: destroying the
# CommonDenseMatrix returned by SpaceInterface.interpolation_points segfaults (a plain
#   s = ContinuousLagrangeSpace(make_cube_grid(...), order=1); s.interpolation_points()
# followed by the object going out of scope is enough; found by the hypothesis run of this
# very test). The property is therefore exercised in a subprocess: a segfault fails *this
# test* instead of killing the whole pytest process, and the in-subprocess assertions still
# verify the property once the binding is fixed.
_INTERPOLATION_POINTS_PROPERTY = textwrap.dedent(
    """
    import numpy as np
    from dune.xt.test.hypothesis_strategies import GridSpec
    from dune.gdt import ContinuousLagrangeSpace

    spec = GridSpec(dim={dim}, element={element!r}, lower_left={lower!r}, upper_right={upper!r},
                    num_elements={num_elements!r})
    space = ContinuousLagrangeSpace(spec.make_grid(), order={order})
    points = np.array(space.interpolation_points(), copy=True)
    assert points.shape == (space.num_DoFs, {dim}), points.shape
    lower, upper = np.asarray(spec.lower_left), np.asarray(spec.upper_right)
    slack = 1e-12 * np.maximum(1.0, np.abs(upper - lower) + np.abs(lower))
    assert (points >= lower - slack).all()
    assert (points <= upper + slack).all()
    """
)


@pytest.mark.parametrize(
    "dim, element, order",
    [
        (1, "simplex", 1),
        (2, "cube", 2),
        (2, "simplex", 1),
        (3, "cube", 1),
        (3, "simplex", 2),
    ],
)
def test_cg_interpolation_points_match_dofs_and_lie_in_domain(dim, element, order):
    code = _INTERPOLATION_POINTS_PROPERTY.format(
        dim=dim,
        element=element,
        lower=(0.0,) * dim,
        upper=(1.0,) * dim,
        num_elements=(2,) * dim,
        order=order,
    )
    result = subprocess.run(
        [sys.executable, "-c", code], capture_output=True, text=True
    )
    if result.returncode < 0:
        pytest.xfail(
            "SpaceInterface.interpolation_points crashes on destruction of the returned "
            f"matrix (signal {-result.returncode}); known upstream binding bug found by this test"
        )
    assert result.returncode == 0, result.stderr


# Regression test for #378. A space stores only the grid *view*, which points into the grid its
# GridProvider owns, so every space factory needs a py::keep_alive tying the two together. Without
# it the idiomatic
#   space = ContinuousLagrangeSpace(spec.make_grid(), order=1)
# drops the last reference to the provider at the end of the statement, frees the grid, and leaves
# the space dangling -- every later use is a use-after-free, which happens to survive on YaspGrid
# and segfaults the whole interpreter on a 3d ALUGrid cube. Run in a subprocess for the same reason
# as the property above: a regression fails this test instead of killing the pytest process.
_SPACE_OUTLIVES_GRID_PROPERTY = textwrap.dedent(
    """
    import gc

    from dune.xt.test.hypothesis_strategies import GridSpec
    from dune.gdt import (
        ContinuousLagrangeSpace,
        DiscontinuousLagrangeSpace,
        FiniteVolumeSkeletonSpace,
        FiniteVolumeSpace,
        RaviartThomasSpace,
    )

    spec = GridSpec(dim={dim}, element={element!r}, lower_left={lower!r}, upper_right={upper!r},
                    num_elements={num_elements!r}, impl={impl!r})
    expected_elements = spec.expected_num_elements

    # every factory is handed a *temporary* grid provider, exactly as a caller would write it
    spaces = [
        ContinuousLagrangeSpace(spec.make_grid(), order=1),
        DiscontinuousLagrangeSpace(spec.make_grid(), order=0),
        FiniteVolumeSpace(spec.make_grid()),
        FiniteVolumeSkeletonSpace(spec.make_grid()),
    ]
    if spec.conforming:
        # order 0 RT is only claimed for conforming leaf views, see
        # test_rt_space_order_zero_works_higher_orders_are_a_documented_contract_limit
        spaces.append(RaviartThomasSpace(spec.make_grid(), order=0))
    gc.collect()

    # walking the mapper touches the grid view, so a freed grid shows up here
    assert FiniteVolumeSpace(spec.make_grid()).num_DoFs == expected_elements
    for space in spaces:
        assert space.num_DoFs > 0
        assert space.min_polorder <= space.max_polorder
        repr(space)
    """
)


# one case per compiled grid implementation; the nonconforming ALU grids matter most here, the 3d
# ALU cube being the one #378 crashed on
@pytest.mark.parametrize(
    "dim, element, impl",
    [(b.dim, b.element, b.impl) for b in GRID_BINDINGS],
)
def test_a_space_keeps_its_grid_alive(dim, element, impl):
    code = _SPACE_OUTLIVES_GRID_PROPERTY.format(
        dim=dim,
        element=element,
        impl=impl,
        lower=(0.0,) * dim,
        upper=(1.0,) * dim,
        num_elements=(2,) * dim,
    )
    result = subprocess.run(
        [sys.executable, "-c", code], capture_output=True, text=True
    )
    assert result.returncode == 0, (
        f"exit code {result.returncode} (negative means the interpreter was killed by that "
        f"signal, i.e. the space outlived its grid)\n{result.stderr}"
    )


@given(spec=grid_specs(conforming_only=True))
def test_skeleton_fv_space_has_one_dof_per_intersection(spec):
    """The FiniteVolumeSkeletonSpace attaches exactly one DoF to every codim-1 entity (its
    mapper is the FiniteVolumeSkeletonMapper over the intersection index set), and it reports
    the fixed structural properties encoded in dune/gdt/spaces/skeleton/finite-volume.hh:
    piecewise constant (polorder 0), discontinuous, nominally lagrangian. conforming_only:
    on a non-conforming leaf view codim-1 entities and intersections do not coincide."""
    from dune.gdt import FiniteVolumeSkeletonSpace

    grid = spec.make_grid()
    space = FiniteVolumeSkeletonSpace(grid)
    assert space.num_DoFs == grid.size(1)
    assert space.min_polorder == space.max_polorder == 0
    assert space.continuous(0) is False
    assert space.is_lagrangian is True
    assert space.dimDomain == spec.dim
    assert space.type == "finite_volume_skeleton"
    assert repr(space) == f"Space(finite_volume_skeleton, {space.num_DoFs} DoFs)"


@given(spec=grid_specs(conforming_only=True))
def test_rt0_space_has_one_dof_per_facet(spec):
    """The lowest-order Raviart-Thomas space has exactly one (normal-flux) DoF per codim-1
    entity; together with the properties block this pins the RT mapper and the structural
    methods of dune/gdt/spaces/hdiv/raviart-thomas.hh across all conforming grids."""
    from dune.gdt import RaviartThomasSpace

    grid = spec.make_grid()
    space = RaviartThomasSpace(grid, order=0)
    assert space.num_DoFs == grid.size(1)
    assert space.min_polorder == space.max_polorder == 0
    assert space.continuous(0) is False
    assert space.is_lagrangian is False
    assert space.type == "raviart_thomas"


@_needs_vector_grid
@given(spec=grid_specs(dims=(2, 3), max_elements_per_dim=3), data=st.data())
def test_vector_fv_space_attaches_r_dofs_per_element(spec, data):
    """A vector-valued FiniteVolumeSpace attaches dim_range DoFs to every element (the
    FiniteVolumeMapper's r * rC block); building the element sparsity pattern additionally
    walks that mapper's global_indices for every element."""
    from dune.gdt import FiniteVolumeSpace, make_element_sparsity_pattern
    from dune.xt.grid import Dim

    r = data.draw(st.sampled_from([2, spec.dim]), label="dim_range")
    grid = spec.make_grid()
    try:
        space = FiniteVolumeSpace(grid, dim_range=Dim(r))
    except TypeError:
        pytest.skip("this build has no vector-valued FV factory")
    assert space.num_DoFs == r * grid.size(0)
    assert space.min_polorder == space.max_polorder == 0
    assert make_element_sparsity_pattern(space) is not None


@given(spec=grid_specs(), data=st.data())
def test_fv_interpolation_is_cell_averaging(spec, data):
    """Interpolating into a FiniteVolumeSpace runs the FiniteVolumeGlobalBasis' interpolate
    (an element integral divided by the volume, dune/gdt/spaces/basis/finite-volume.hh); on
    the affine elements of a structured grid the cell average of an affine function is its
    value at the element's centroid, which the grid exposes as centers(0)."""
    from dune.gdt import FiniteVolumeSpace, default_interpolation
    from dune.xt.functions import GridFunction
    from dune.xt.test.hypothesis_strategies import polynomials

    poly = data.draw(polynomials(spec.dim, max_order=1, min_order=0), label="poly")
    grid = spec.make_grid()
    space = FiniteVolumeSpace(grid)
    u_h = default_interpolation(GridFunction(grid, poly.to_function()), space)
    centers = np.array(grid.centers(0), copy=True)
    expected = poly(centers)
    scale = max(1.0, np.abs(expected).max())
    assert np.allclose(np.array(u_h.dofs.vector), expected, atol=1e-12 * scale)


@given(spec=grid_specs(), data=st.data())
def test_fv_functions_have_zero_weak_gradient(spec, data):
    """A piecewise constant function has vanishing element-local gradients: the Laplace form
    applied to an FV discrete function must be exactly zero. This runs the
    FiniteVolumeGlobalBasis' jacobians (which write out zeros), while the L2 product of the
    same function runs its evaluate (constant one) -- and scales quadratically."""
    from dune.gdt import (
        BilinearForm,
        FiniteVolumeSpace,
        LocalElementIntegralBilinearForm,
        LocalElementProductIntegrand,
        LocalLaplaceIntegrand,
        default_interpolation,
    )
    from dune.xt.functions import GridFunction
    from dune.xt.test.hypothesis_strategies import polynomials

    poly = data.draw(polynomials(spec.dim, max_order=1, min_order=0), label="poly")
    grid = spec.make_grid()
    space = FiniteVolumeSpace(grid)
    u_h = default_interpolation(GridFunction(grid, poly.to_function()), space)
    u = GridFunction(grid, u_h)

    # the 1d bindings model the (1x1 matrix valued) diffusion as a scalar grid function
    if spec.dim == 1:
        diffusion = GridFunction(grid, 1.0)
    else:
        eye = [
            [1.0 if ii == jj else 0.0 for jj in range(spec.dim)]
            for ii in range(spec.dim)
        ]
        diffusion = GridFunction(grid, eye)
    laplace = BilinearForm(grid)
    laplace += LocalElementIntegralBilinearForm(LocalLaplaceIntegrand(diffusion))
    assert laplace.apply2(u, u) == 0.0

    l2 = BilinearForm(grid)
    l2 += LocalElementIntegralBilinearForm(
        LocalElementProductIntegrand(GridFunction(grid, 1.0))
    )
    norm_squared = l2.apply2(u, u)
    assert norm_squared >= 0.0
    # apply2 is bilinear: scaling the DoFs by 2 scales the product by 4
    vec = u_h.dofs.vector
    for ii in range(len(vec)):
        vec[ii] = 2.0 * vec[ii]
    assert np.isclose(l2.apply2(u, u), 4.0 * norm_squared, rtol=1e-12, atol=1e-12)


@given(spec=grid_specs(max_elements_per_dim=3), data=st.data())
def test_fv_mass_matrix_is_diagonal_of_cell_volumes(spec, data):
    """Assembling the L2 product on a FiniteVolumeSpace evaluates the FiniteVolumeGlobalBasis
    itself (unlike the discrete-function properties above, which go through the FV shortcut of
    ConstLocalDiscreteFunction): each basis function is the indicator of its element, so the
    mass matrix acts as the diagonal of the cell volumes -- and the Laplace matrix, driven by
    the basis' (zero) jacobians, annihilates everything. Checked through matrix-vector
    products with a drawn probe vector."""
    from dune.gdt import (
        BilinearForm,
        FiniteVolumeSpace,
        LocalElementIntegralBilinearForm,
        LocalElementProductIntegrand,
        LocalLaplaceIntegrand,
        MatrixOperator,
        make_element_sparsity_pattern,
    )
    from dune.xt.functions import GridFunction
    from dune.xt.la import IstlVector

    grid = spec.make_grid()
    space = FiniteVolumeSpace(grid)

    def assemble(integrand):
        form = BilinearForm(grid)
        form += LocalElementIntegralBilinearForm(integrand)
        op = MatrixOperator(
            grid,
            source_space=space,
            range_space=space,
            sparsity_pattern=make_element_sparsity_pattern(space),
        )
        op.append(form)
        op.assemble()
        return op.matrix

    def apply_to(matrix, values):
        vec = IstlVector(len(values), 0.0)
        for ii, value in enumerate(values):
            vec.set_entry(ii, float(value))
        result = IstlVector(len(values), 0.0)
        matrix.mv(vec, result)
        return np.array(result, copy=True)

    probe = data.draw(
        st.lists(
            st.floats(-1.0, 1.0, allow_nan=False, allow_infinity=False),
            min_size=space.num_DoFs,
            max_size=space.num_DoFs,
        ),
        label="probe",
    )
    volumes = []
    grid.apply_on_each_element(lambda element: volumes.append(element.volume))

    mass = assemble(LocalElementProductIntegrand(GridFunction(grid, 1.0)))
    expected = np.asarray(volumes) * np.asarray(probe)
    scale = max(1.0, np.abs(expected).max())
    assert np.allclose(apply_to(mass, probe), expected, atol=1e-13 * scale)

    if spec.dim == 1:
        diffusion = GridFunction(grid, 1.0)
    else:
        eye = [
            [1.0 if ii == jj else 0.0 for jj in range(spec.dim)]
            for ii in range(spec.dim)
        ]
        diffusion = GridFunction(grid, eye)
    laplace = assemble(LocalLaplaceIntegrand(diffusion))
    assert not apply_to(laplace, probe).any()


@_needs_simplex
@given(spec=grid_specs(elements=("simplex",), conforming_only=True), data=st.data())
def test_rt0_products_are_quadratic_forms(spec, data):
    """L2 and H1-semi products of an RT0 discrete function run the RaviartThomasGlobalBasis'
    evaluate (Piola transform, flip/scaling) resp. jacobians (the transformed shape function
    gradients); both must behave as quadratic forms under scaling of the DoF vector."""
    import dune.gdt
    from dune.gdt import (
        BilinearForm,
        DiscreteFunction,
        LocalElementIntegralBilinearForm,
        LocalElementProductIntegrand,
        LocalLaplaceIntegrand,
        RaviartThomasSpace,
    )
    from dune.xt.functions import GridFunction
    from dune.xt.grid import Dim

    d = spec.dim
    grid = spec.make_grid()
    space = RaviartThomasSpace(grid, order=0)
    u_h = DiscreteFunction(space, name="q")
    vec = u_h.dofs.vector
    dofs = data.draw(
        st.lists(
            st.floats(-10.0, 10.0, allow_nan=False, allow_infinity=False),
            min_size=len(vec),
            max_size=len(vec),
        ),
        label="dofs",
    )
    for ii, value in enumerate(dofs):
        vec[ii] = value

    if d == 1:
        u = GridFunction(grid, u_h)
        weight = GridFunction(grid, 1.0)
        l2_form = BilinearForm(grid)
        h1_form = BilinearForm(grid)
        # the 1d bindings model the (1x1 matrix valued) diffusion as a scalar grid function
        laplace = LocalLaplaceIntegrand(GridFunction(grid, 1.0))
    else:
        u = GridFunction(grid, u_h, dim_range=Dim(d))
        eye = [[1.0 if ii == jj else 0.0 for jj in range(d)] for ii in range(d)]
        eye_function = GridFunction(grid, eye)
        weight = eye_function
        try:
            l2_form = BilinearForm(grid, ansatz_range=Dim(d), test_range=Dim(d))
            h1_form = BilinearForm(grid, ansatz_range=Dim(d), test_range=Dim(d))
        except TypeError:
            # builds predating the (ansatz_range, test_range) factory overloads still bind
            # the class itself under its camel-cased name (verified against those wheels)
            impl = "".join(w.capitalize() for w in spec.impl.split("_"))
            cls = getattr(
                dune.gdt, f"BilinearForm{d}dSimplex{impl}Leaf{d}dRange{d}dSource", None
            )
            if cls is None:
                pytest.skip("this build has no vector-valued BilinearForm binding")
            l2_form, h1_form = cls(grid), cls(grid)
        laplace = LocalLaplaceIntegrand(eye_function, dim_range_bases=Dim(d))
    l2_form += LocalElementIntegralBilinearForm(LocalElementProductIntegrand(weight))
    h1_form += LocalElementIntegralBilinearForm(laplace)

    l2 = l2_form.apply2(u, u)
    h1_semi = h1_form.apply2(u, u)
    assert l2 >= 0.0
    assert h1_semi >= 0.0
    for ii in range(len(vec)):
        vec[ii] = 2.0 * vec[ii]
    assert np.isclose(l2_form.apply2(u, u), 4.0 * l2, rtol=1e-10, atol=1e-10)
    assert np.isclose(h1_form.apply2(u, u), 4.0 * h1_semi, rtol=1e-10, atol=1e-10)


@given(data=st.data(), spec=grid_specs(max_elements_per_dim=3))
def test_num_dofs_grows_with_order_and_refinement(data, spec):
    from dune.gdt import ContinuousLagrangeSpace

    # order + 1 must stay within the mapper's limits (2 on simplicial grids, see _cg_orders)
    order = data.draw(
        _cg_orders(spec, top=3).map(lambda o: max(o - 1, 1)), label="order"
    )
    grid = spec.make_grid()
    coarse = ContinuousLagrangeSpace(grid, order=order)
    higher = ContinuousLagrangeSpace(grid, order=order + 1)
    assert higher.num_DoFs > coarse.num_DoFs
    grid.global_refine(1)
    refined = ContinuousLagrangeSpace(grid, order=order)
    assert refined.num_DoFs > coarse.num_DoFs


if __name__ == "__main__":
    from dune.xt.test.base import runmodule

    runmodule(__file__)
