---
name: build and test

on:
    push:
    #     branches:
    #         - main
    # pull_request:

concurrency:
    group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

env:
    DUNE_BUILD_DIR: /build

jobs:
    matrix-setup:
        runs-on: ubuntu-22.04
        steps:
            - name: Setup matrix combinations
              id: setup-matrix-combinations
              run: |
                  MATRIX_PARAMS_COMBINATIONS='
                      {"CC": "gcc", "CXX": "g++"},
                  '
                  echo ::set-output name=matrix-combinations::{\"include\":[$MATRIX_PARAMS_COMBINATIONS]}
        outputs:
            matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}

    metadata:
        runs-on: ubuntu-22.04
        needs: matrix-setup
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: true
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ghcr.io/${{github.repository}}/ci_test
                  flavor: |
                      latest=false
                  tags: |
                      type=sha,suffix=-g{{branch}}
        outputs:
            tags: ${{steps.meta.outputs.tags}}
    build:
        runs-on: ubuntu-22.04
        needs: [metadata, matrix-setup]
        strategy:
            matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix-combinations) }}
        permissions:
            packages: write
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: true
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Github Packages
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build Image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  file: deps/Dockerfile
                  cache-from: type=registry,ref=ghcr.io/${{github.repository}}/ci_test
                  cache-to: type=inline
                  tags: ${{ needs.metadata.outputs.tags }}_${{matrix.CC}}
                  build-args: |
                      BUILD_CXX=${{matrix.CXX}}
                      BUILD_CC=${{matrix.CC}}
                      DEBIAN_BASE=debian
                      BUILD_OPTS=travis.ninja
    test_cpp:
        runs-on: ubuntu-22.04
        needs: [metadata, matrix-setup, build]
        strategy:
            matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix-combinations) }}
            fail-fast: false
        steps:
            - name: Login to Github Packages
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Setup ccache
              id: ccache-cpp
              uses: actions/cache@v3
              with:
                path: ${{ github.workspace }}/ccache
                key: ${{matrix.CC}}-cpp-ccache
            - name: C++ Tests ${{matrix.CC}}
              run: |
                  docker run --rm \
                    -e DUNE_BUILD_DIR=${DUNE_BUILD_DIR} \
                    -v ${GITHUB_WORKSPACE}/build/testresults/:/build/testresults \
                    -v ${GITHUB_WORKSPACE}/ccache/:/root/.ccache \
                    -e OMPI_ALLOW_RUN_AS_ROOT=1 -e OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
                    ${{ needs.metadata.outputs.tags }}_${{matrix.CC}} \
                    /src/.ci/gitlab/test_cpp.bash
            - uses: actions/upload-artifact@v3
              name: Upload CPP results
              if: always()
              with:
                name: cpp_junit_reports
                path: ${{ github.workspace }}/build/testresults/*xml
    test_headercheck:
        runs-on: ubuntu-22.04
        needs: [metadata, matrix-setup, build]
        strategy:
            matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix-combinations) }}
        steps:
            - name: Login to Github Packages
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Headercheck ${{matrix.CC}}
              run: |
                  docker run --rm \
                    ${{ needs.metadata.outputs.tags }}_${{matrix.CC}} \
                    /src/.ci/gitlab/test_headercheck.bash
    test_python:
        runs-on: ubuntu-22.04
        needs: [metadata, matrix-setup, build]
        strategy:
            matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix-combinations) }}
            fail-fast: false
        steps:
            - name: Login to Github Packages
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Setup ccache
              id: ccache-py
              uses: actions/cache@v3
              with:
                path: ${{ github.workspace }}/ccache
                key: ${{matrix.CC}}-py-ccache
            - name: Python Tests ${{matrix.CC}}
              run: |
                  docker run --rm \
                    -e DUNE_BUILD_DIR=${DUNE_BUILD_DIR} \
                    -v ${GITHUB_WORKSPACE}/ccache/:/root/.ccache \
                    -v ${GITHUB_WORKSPACE}/build/testresults/:/build/testresults \
                    ${{ needs.metadata.outputs.tags }}_${{matrix.CC}} \
                    /src/.ci/gitlab/test_python.bash
            - uses: actions/upload-artifact@v3
              name: Upload Python results
              if: always()
              with:
                name: python_junit_reports
                path: ${{ github.workspace }}/build/testresults/*xml
    wheels:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                python: ["3.8", "3.9", "3.10"]
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: true
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
            - run: |
                source .env
                docker run --rm \
                    -v ${GITHUB_WORKSPACE}/wheelhouse:/wheelhouse \
                    -v ${PWD}:/home/dxt/src \
                    -e WHEEL_DIR=/wheelhouse \
                    -e LOCAL_UID=0 \
                    -e DUNE_SRC_DIR=/home/dxt/src \
                    zivgitlab.wwu.io/ag-ohlberger/dune-community/docker/manylinux-2_28_x86_64_py${{matrix.python}}:${ML_TAG} \
                    /home/dxt/src/.ci/make_wheels.bash
              name: Build Wheel py${{matrix.python}}
            - uses: actions/upload-artifact@v3
              with:
                name: wheels
                path: ${{github.workspace}}/wheelhouse/final/dune*whl

    publish:
        needs: [wheels]
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/download-artifact@v3
              with:
                name: wheels
            - name: PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/20')
              with:
                password: ${{ secrets.PYPI_API_TOKEN }}
                packages_dir: .
                verbose: true
            - name: Test PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                password: ${{ secrets.TEST_PYPI_API_TOKEN }}
                verbose: true
                packages_dir: .
    combine_reports:
      needs: [test_cpp, test_python]
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/download-artifact@v3
          name: Download Python reports
          with:
            name: python_junit_reports
        - uses: actions/download-artifact@v3
          name: Download C++ reports
          with:
            name: cpp_junit_reports
        - uses: actions/setup-node@v3
          with:
            node-version: 16
        - run: npm install -g junit-report-merger
        - run: jrm combined_report.xml "*.xml"
        - uses: actions/upload-artifact@v3
          with:
            name: combined_report
            path: combined_report.xml