---
name: build and test

on:
    push:
    #     branches:
    #         - main
    # pull_request:

concurrency:
    group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

env:
    CI_IMAGE: debian
    OPTS: travis.ninja

jobs:
    matrix-setup:
        runs-on: ubuntu-22.04
        steps:
            - name: Setup matrix combinations
              id: setup-matrix-combinations
              run: |
                  MATRIX_PARAMS_COMBINATIONS='
                      {"CC": "clang", "CXX": "clang++"},
                      {"CC": "gcc", "CXX": "g++"},
                  '
                  echo ::set-output name=matrix-combinations::{\"include\":[$MATRIX_PARAMS_COMBINATIONS]}
        outputs:
            matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}

    metadata:
        runs-on: ubuntu-22.04
        needs: matrix-setup
        steps:
            - uses: actions/checkout@v3
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ghcr.io/${{github.repository}}/ci_test
                  flavor: |
                      latest=false
                  tags: |
                      type=sha,suffix=-g{{branch}}
        outputs:
            tags: ${{steps.meta.outputs.tags}}
    build:
        runs-on: ubuntu-22.04
        needs: [metadata, matrix-setup]
        strategy:
            matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix-combinations) }}
        permissions:
            packages: write
        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Github Packages
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  file: deps/Dockerfile
                  tags: ${{ needs.metadata.outputs.tags }}_${{matrix.CC}}
                  build-args: |
                      BUILD_CXX=${{matrix.CXX}}
                      BUILD_CC=${{matrix.CC}}
                      DEBIAN_BASE=${{CI_IMAGE}}
                      BUILD_OPTS=${{OPTS}}
    test_cpp:
        runs-on: ubuntu-22.04
        needs: [metadata, matrix-setup, build]
        strategy:
            matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix-combinations) }}
        steps:
            - name: Login to Github Packages
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Test
              run: |
                  docker run --rm ${{ needs.metadata.outputs.tags }}_${{matrix.CC}} /src/.ci/gitlab/test_cpp.bash
    test_headercheck:
        runs-on: ubuntu-22.04
        needs: [metadata, matrix-setup, build]
        strategy:
            matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix-combinations) }}
        steps:
            - name: Login to Github Packages
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Test
              run: |
                  docker run --rm ${{ needs.metadata.outputs.tags }}_${{matrix.CC}} /src/.ci/gitlab/test_headercheck.bash
    test_python:
        runs-on: ubuntu-22.04
        needs: [metadata, matrix-setup, build]
        strategy:
            matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix-combinations) }}
        steps:
            - name: Login to Github Packages
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Test
              run: |
                  docker run --rm ${{ needs.metadata.outputs.tags }}_${{matrix.CC}} /src/.ci/gitlab/test_python.bash
    wheels:
        runs-on: ubuntu-22.04
        env:
            LOCAL_UID: 0
        strategy:
            matrix:
                python: ["3.8", "3.9", "3.10"]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
            - run: |
                source .env
                docker run --rm \
                    -v ${{GITHUB_WORKSPACE}}/wheelhouse:/wheelhouse \
                    -e WHEEL_DIR=wheelhouse \
                    zivgitlab.wwu.io/ag-ohlberger/dune-community/docker/manylinux-2_28_x86_64_py${{matrix.python}:${ML_TAG} \
                    ./.ci/make_wheels.bash

            - uses: actions/upload-artifact@v3
              with:
                name: wheels
                path: ${{GITHUB_WORKSPACE}}/wheelhouse/final/dune*whl