---
# homepage: https://github.com/gaurav-nelson/github-action-markdown-link-check
name: Check links in Markdown files

on: [pull_request]

jobs:
  markdown-link-check:
    name: Markdown
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout reposotiry
      uses: actions/checkout@v3
    - name: Check links in Markdown files
      uses: renefritze/github-action-markdown-link-check@master
      with:
        use-verbose-mode: yes
        base-branch: main
        check-modified-files-only: yes
        config-file: .github/markdown_link_check_config.json
