name: cleanup_pypi

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup_pypi:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pypi-cleanup
      - name: Cleanup PyPI
        run: |
          pypi-cleanup --username ${{ secrets.TEST_PYPI_USERNAME }} --host https://test.pypi.org/ --package dune-gdt
          pypi-cleanup --username ${{ secrets.TEST_PYPI_USERNAME }} --host https://test.pypi.org/ --package dune-xt
        env:
          PYPI_CLEANUP_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
