name: "Docker: build images"

on:
  workflow_dispatch:
    inputs:
      GIT_REF:
        description: "Git ref to use as a basis"
        required: False
        default: "main"
jobs:
  docker_build_images:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.GIT_REF }}
      -
        name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Print debug information
        run: |
          echo "Git status:" && git status && \
          echo "\n\nGit ref: " && git log -1 --pretty=format:"%H" && \
          echo "\n\nDev hash: " && ./docker/compute_dev_hash.sh && \
          sha256sum ./docker/dev/* compute_dev_hash.sh | sha256sum | cut -d ' ' -f 1
      -
        name: Upload dev artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dev
          path: |
            ./docker/dev
            ./docker/compute_ci_hash.sh
      -
        name: Upload ci artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ci
          path: |
            ./docker/ci
            ./docker/compute_ci_hash.sh
      -
        name: Upload opts artifacts
        uses: actions/upload-artifact@v3
        with:
          name: opts
          path: |
            ./deps/config.opts
      # -
      #   name: Build dev image
      #   run: ./docker/build_dev.sh
      # -
      #   name: Publish dev image
      #   run: docker push ghcr.io/${{ github.repository }}/dev:$(./docker/compute_dev_hash.sh)
      # -
      #   name: Build ci image
      #   run: ./docker/build_ci.sh
      # -
      #   name: Publish ci image
      #   run: docker push ghcr.io/${{ github.repository }}/ci:$(./docker/compute_ci_hash.sh)