---
name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main, ci_tutorials]
    types:
        - completed

jobs:
    pages:
      permissions:
        pages: write  # to deploy to Pages
        id-token: write  # to verify the deployment originates from an appropriate source
      environment:
        name: github-22.04
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - uses: dawidd6/action-download-artifact@v2.28.0
          with:
            workflow: dependencies_change.yml
            run_id: ${{ github.event.workflow_run.id }}
            name: tutorials_html
            path: .
        - name: Setup Pages
          uses: actions/configure-pages@v3
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
          with:
            # Upload entire repository
            path: 'html'
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
