---
name: Wheels

on:
    push:
    #     branches:
    #         - main
    # pull_request:

concurrency:
    group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    wheels:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                python: ["3.8", "3.9", "3.10"]
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: true
                # version info generation needs potentially all commits
                fetch-depth: 0
            - name: Get tags
              run: git fetch --tags origin
            - run: |
                git describe --tags --dirty --always --long --match "*"
