---
name: Wheels

on:
    push:
    #     branches:
    #         - main
    # pull_request:

concurrency:
    group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    wheels:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                python: ["3.8", "3.9", "3.10", "3.11"]
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: true
                # version info generation needs potentially all commits
                fetch-depth: 0
            - name: Get tags
              if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
              run: git fetch --tags origin
            - name: Setup ccache
              id: ccache-wheel
              uses: actions/cache@v3
              with:
                path: ${{ github.workspace }}/wheelhouse/cache
                key: ${{matrix.python}}-wheel-ccache
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
            - run: |
                git config --global --add safe.directory '*'
                source .env
                docker run --rm \
                    -v ${GITHUB_WORKSPACE}/wheelhouse:/wheelhouse \
                    -v ${PWD}:/home/dxt/src \
                    -e WHEEL_DIR=/wheelhouse \
                    -e CCACHE_DEBUG=1 \
                    -e GITHUB_RUN_NUMBER \
                    -e LOCAL_UID=0 \
                    -e DUNE_SRC_DIR=/home/dxt/src \
                    -e CI \
                    ${ML_IMAGE_BASE}_py${{matrix.python}}:${ML_TAG} \
                    /home/dxt/src/.ci/make_wheels.bash
              name: Build Wheel py${{matrix.python}}
            - uses: actions/upload-artifact@v3
              with:
                name: wheels
                path: ${{github.workspace}}/wheelhouse/final/dune*whl
            - uses: actions/upload-artifact@v3
              with:
                name: ccache-log_${{matrix.python}}
                path: ${{github.workspace}}/docker/build/dune-gdt/**/*ccache-log
    test:
        needs: [wheels]
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                name: wheels
            - uses : actions/setup-python@v2
              with:
                python-version: 3.9
            - name: Install dependencies
              run: |
                ls -l
                python -m pip install --upgrade pip
                pip install pytest
                pip install dune*xt*whl
                pip install dune*gdt*whl
            - name: Test with pytest
              run: |
                pytest -v ./python/dune/gdt/test/test_version.py

    publish:
        needs: [test]
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/download-artifact@v3
              with:
                name: wheels
            - name: split by package
              run: |
                mkdir xt gdt
                mv *xt*.whl xt/
                mv *gdt*.whl gdt
            - name: XT PyPI
              uses: pypa/gh-action-pypi-publish@v1.6.4
              if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/20')
              with:
                password: ${{ secrets.XT_PYPI_API_TOKEN }}
                packages_dir: xt
                verbose: true
            - name: XT Test PyPI
              uses: pypa/gh-action-pypi-publish@v1.6.4
              if: ${{ ! startsWith(github.ref, 'refs/tags/20') }}
              with:
                password: ${{ secrets.XT_TEST_PYPI_API_TOKEN }}
                verbose: true
                packages_dir: xt
                repository_url: https://test.pypi.org/legacy/
            - name: GDT PyPI
              uses: pypa/gh-action-pypi-publish@v1.6.4
              if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/20')
              with:
                password: ${{ secrets.GDT_PYPI_API_TOKEN }}
                packages_dir: gdt
                verbose: true
            - name: GDT Test PyPI
              uses: pypa/gh-action-pypi-publish@v1.6.4
              if: ${{ ! startsWith(github.ref, 'refs/tags/20') }}
              with:
                password: ${{ secrets.GDT_TEST_PYPI_API_TOKEN }}
                verbose: true
                packages_dir: gdt
                repository_url: https://test.pypi.org/legacy/

