# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v13.0.0'
    hooks:
    -   id: clang-format
        exclude: "^(dune/xt/test/gtest/|pybind11)"
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
    -   id: yapf
        args: ["--style=.vcsetup/.style.yapf"]
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: 'v0.6.13'
    hooks:
    -   id: cmake-format
        additional_dependencies: [pyyaml>=5.1] # see https://github.com/cheshirekow/cmake-format-precommit/pull/4#issuecomment-943444582
        exclude: "config.h.cmake|pybind11"
        args: ["-i", "--config-files=.cmake_format.py"]
    -   id: cmake-lint
        additional_dependencies: [pyyaml>=5.1] # see https://github.com/cheshirekow/cmake-format-precommit/pull/4#issuecomment-943444582
        exclude: "config.h.cmake|pybind11"
        args: ["--config-files=.cmake_format.py"]
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        exclude: "^pybind11"
        args: ["--config=./python/setup.cfg"]
